### ISSUE TITLE
DeprecationWarning showing up in tests regardless of templates used?

### ISSUE THREAD

**Issue by hannylicious** [jazzband/django-simple-menu#147]
When I run my tests I see this:

`DeprecationWarning: The 'menu' template library will be removed in django-simple-menu v2.3 and/or v3.0. Use '{% load simple_menu %}' instead.`

I've went through all of my templates and ensured that there is no `load menu` and that all instances were replaced with `load simple_menu` as per the docs and per the warning.

I've gone over my code pretty exhaustively and can find absolutely no template references to 'menu' in the templates. Everywhere we use django-simple-menu in a template has `load simple_menu`.

In any test that uses the test client / UI in any fashion that warning appears.

Am I missing something obvious to get that warning to go away?

**Comment by kytta** [comment]
Hey Hanny! No, you're not missing anything, the warning appears even if everything is done correctly :S I do not know why that happens, and honestly, it is time to remove the old package and release a major version dropping dj32 support... I'll see if I find time to go through the backlog here 😅

**Comment by hannylicious** [comment]
No worries (and no rush!); the warnings have been something I've seen for quite some time and I just had a moment and figured I would ask if I was missing something - trying to cleanup some older projects and refactor things where appropriate.

I appreciate the quick response!
