### ISSUE TITLE
Example not working as in readme

### ISSUE THREAD

**Issue by Boldie** [jazzband/django-simple-menu#49]
Trying your example on ubuntu 16.04 as in the README.rst just brings the following:

>./manage.py syncdb
Unknown command: 'syncdb'
Type 'manage.py help' for usage.

**Comment by kytta** [comment]
`syncdb` has been deprecated since Django 1.7 and removed in the following versions. One should instead use:

```sh
python manage.py migrate
```

---

As one can see, the example app and its docs are pretty old and need to be updated. Follow #51 for updates. Closing this issue for now.
