### ISSUE TITLE
Update example app to Django 3.2 (or 4.0)

### ISSUE THREAD

**Issue by marcoracer** [jazzband/django-simple-menu#51]
Could you please update the example code to run under new django 1.10+ requirements?

**Comment by ianastewart** [comment]
Only thing that I had to change to run this with Django 2.1 / Python 3.7 was the import in `example.accounts.menus.py`
Old : `from django.core.urlresolvers import reverse`
New: `from django.urls import reverse `

If you don't change this, the import fails and your menus get ignored

**Comment by kytta** [comment]
The project hasn't seen any activity in a while. I'm going to work on it in order to bring it in a better shape.

The planned release 2.0.0 will support Django starting with v3.2. Thus, the task now is to update the example app to Django 3.2 (or 4.0).
