### ISSUE TITLE
'cmp' is an invalid keyword argument for this function

### ISSUE THREAD

**Issue by aburcheri** [jazzband/django-simple-menu#57]
Have some trouble using the template tag do render the menu:

> 'cmp' is an invalid keyword argument for this function

seems like cmp is not more valid

**Comment by kytta** [comment]
It seems like you're using the old version: this issue has been fixed in #20. The oldest version that has these changes is 1.1.0, the newest is 1.2.0.

**Comment by kytta** [comment]
Since this issue was solved in #20 and concers now-dead Python 2, I'll close it.
