### ISSUE TITLE
generate_menu not working

### ISSUE THREAD

**Issue by hgarcia101685** [jazzband/django-simple-menu#64]
Hi, 
I've followed the examples pretty closely and am not able to get menus to generate.  I've put some logic around the code in order to see where things are failing and it appears that everything gets stuck on this line: {% generate_menu %}

          {% load menu %}

{% block content %}
          <p>once</p>
          {% load menu %}
          <p>two</p>
{% generate_menu %}
          <p>three</p>
  <ul>
    {% for item in menu %}
    <p>booyah</p>
    {% if item.separator %}<li>------------</li>{% endif %}
    <li><a href="{{ item.url }}">{{ item.title }}</a></li>
    {% endfor %}
</ul>
{% endblock %}

**Comment by Pfeilsticker** [comment]
I've the same problem.
[see stackoverflow](https://stackoverflow.com/questions/60901630/q-django-simple-menu-menu-doesnt-load)

**Comment by DanishAbsar** [comment]
Hi @hgarcia101685 and @Pfeilsticker 

May I know you django and python version ?

**Comment by Pfeilsticker** [comment]
Hi @DanishAbsar ,

I use 
Django: 3.0.1
Python: 3.7.5

**Comment by DanishAbsar** [comment]
> 
> 
> Hi @DanishAbsar ,
> 
> I use
> Django: 3.0.1
> Python: 3.7.5

Ah okay, so please update the following things in your menus.py (which belongs to the app)
replace this
`from django.core.urlresolvers import reverse`
with this
`from django.urls import reverse`

**Comment by kytta** [comment]
Closing for the lack of activity. If the issue still remains, please, let me know and I'll reopen it.
