### ISSUE TITLE
Rename the Python module?

### ISSUE THREAD

**Issue by kytta** [jazzband/django-simple-menu#90]
IMO, the current name of the Python module (`menu`) is too broad. I can imagine people using it for their own Python modules or Django apps (think of a restaurant website with an app for menus).

I propose renaming the Python module to `simple_menu`, similarly to how many other Django packages do it.

EDIT: of course, we will need to bump the major version, but we do it anyway with the v2.0.0 release

**Comment by mbeijen** [comment]
Hi, I would be a proponent of this, indeed the name is too generic otherwise.

I'd propose to _also_ allow using the include in the old way, for the time being, with a deprecation warning.

**Comment by mbeijen** [comment]
Thanks kytta for your work, this is now in 2.0.1 on pypi!
